const gameData = {
    'truth-or-dare': {
        title: 'Truth or Dare',
        normal: [
            { type: 'Truth', text: 'What is the most romantic thing {partner} has ever done for you?' },
            { type: 'Truth', text: 'What was your first impression of {partner}?' },
            { type: 'Truth', text: 'What is one thing you are most proud of in our relationship?' },
            { type: 'Truth', text: 'If you could change one thing about our daily routine, what would it be?' },
            { type: 'Truth', text: 'What is your favorite memory of us together?' },
            { type: 'Truth', text: 'What is a secret dream you have for our future?' },
            { type: 'Truth', text: 'What is the best piece of advice you have ever received?' },
            { type: 'Truth', text: 'What is something you wish you knew earlier about love?' },
            { type: 'Truth', text: 'How do you feel most loved by {partner}?' },
            { type: 'Truth', text: 'What is your favorite personality trait of {partner}?' },
            { type: 'Truth', text: 'What is a goal you have for us for the next year?' },
            { type: 'Truth', text: 'What is the most meaningful gift you have ever received from {partner}?' },
            { type: 'Truth', text: 'If we could move anywhere, where would you choose?' },
            { type: 'Truth', text: 'What is your favorite way to spend a weekend?' },
            { type: 'Truth', text: 'What do you admire most about your own parents?' },
            { type: 'Truth', text: 'What is a simple habit you want to start together?' },
            { type: 'Truth', text: 'What was your favorite childhood vacation?' },
            { type: 'Truth', text: 'What is a song that always reminds you of us?' },
            { type: 'Truth', text: 'What is a skill you have always wanted to learn together?' },
            { type: 'Truth', text: 'What does a perfect day look like to you?' },
            { type: 'Truth', text: 'What is the kindest thing a stranger has ever done for you?' },
            { type: 'Truth', text: 'What is a challenge you have overcome and what did it teach you?' },
            { type: 'Truth', text: 'What is your favorite family tradition?' },
            { type: 'Truth', text: 'What is something you think we should do more often?' },
            { type: 'Truth', text: 'What was the first thing that made you laugh about {partner}?' },
            { type: 'Truth', text: 'What is a book or movie that changed your perspective on life?' },
            { type: 'Truth', text: 'How do you handle stress, and how can {partner} support you?' },
            { type: 'Truth', text: 'What is your favorite part of {partner}’s daily routine?' },
            { type: 'Truth', text: 'What does "home" mean to you?' },
            { type: 'Truth', text: 'If you could have dinner with anyone, who would it be?' },
            { type: 'Truth', text: 'What is your proudest non-relationship accomplishment?' },
            { type: 'Truth', text: 'What is a small detail about {partner} that you adore?' },
            { type: 'Truth', text: 'What is the most relaxing place you have ever been?' },
            { type: 'Truth', text: 'What is one thing you are grateful for today?' },
            { type: 'Truth', text: 'What is a dream job you would love to have?' },
            { type: 'Truth', text: 'How do you define happiness?' },
            { type: 'Truth', text: 'What is your favorite type of weather for a date?' },
            { type: 'Truth', text: 'What is a talent you wish you had?' },
            { type: 'Truth', text: 'If you could travel to the past, where would you go?' },
            { type: 'Truth', text: 'What is the most beautiful thing you have ever seen?' },
            { type: 'Truth', text: 'What makes you feel most energized?' },
            { type: 'Truth', text: 'What is your favorite way to help others?' },
            { type: 'Truth', text: 'What is one value you hope to pass on to others?' },
            { type: 'Truth', text: 'What is a hobby that truly relaxes you?' },
            { type: 'Truth', text: 'What is your earliest childhood memory?' },
            { type: 'Truth', text: 'What is a secret talent you keep hidden?' },
            { type: 'Truth', text: 'If you could have any pet, what would it be?' },
            { type: 'Truth', text: 'What is a project you want to start this month?' },
            { type: 'Truth', text: 'How do you want to be remembered?' },
            { type: 'Truth', text: 'What is one thing {partner} does that makes you smile instantly?' },
            { type: 'Dare', text: 'Give {partner} a 2-minute foot massage.' },
            { type: 'Dare', text: 'Write down three things you love about {partner} and read them aloud.' },
            { type: 'Dare', text: 'Slow dance with {partner} to a song of your choice.' },
            { type: 'Dare', text: 'Give {partner} a compliment for every letter of the alphabet.' },
            { type: 'Dare', text: 'Plan our next date night, including food and activity.' },
            { type: 'Dare', text: 'Draw a picture of {partner} as a superhero.' },
            { type: 'Dare', text: 'Serenade {partner} with a song, even if you can’t sing.' },
            { type: 'Dare', text: 'Give {partner} a long, passionate hug right now.' },
            { type: 'Dare', text: 'Tell {partner} a story about your childhood.' },
            { type: 'Dare', text: 'Make a coffee or tea for {partner} exactly how they like it.' },
            { type: 'Dare', text: 'Write {partner} a short, sweet poem.' },
            { type: 'Dare', text: 'Cook a surprise dessert for {partner}.' },
            { type: 'Dare', text: 'Give {partner} a genuine, heartfelt compliment.' },
            { type: 'Dare', text: 'Take a selfie with {partner} right now.' },
            { type: 'Dare', text: 'Create a "top 5" list of things you love about our life.' },
            { type: 'Dare', text: 'Give {partner} a relaxing shoulder massage.' },
            { type: 'Dare', text: 'Tell {partner} about your biggest aspiration.' },
            { type: 'Dare', text: 'Leave a surprise note for {partner} in their bag.' },
            { type: 'Dare', text: 'Show {partner} a video that makes you feel happy.' },
            { type: 'Dare', text: 'Walk around the block holding hands.' },
            { type: 'Dare', text: 'Read aloud a page from a book you love.' },
            { type: 'Dare', text: 'Give {partner} a kiss on the forehead.' },
            { type: 'Dare', text: 'Prepare a healthy snack to share.' },
            { type: 'Dare', text: 'Look through an old photo album with {partner}.' },
            { type: 'Dare', text: 'Pick a movie for our next night in.' },
            { type: 'Dare', text: 'Write down one thing you want to do together next weekend.' },
            { type: 'Dare', text: 'Clean one area {partner} has been wanting to organize.' },
            { type: 'Dare', text: 'Give {partner} a scalp massage.' },
            { type: 'Dare', text: 'Bring {partner} a glass of water.' },
            { type: 'Dare', text: 'Tell {partner} why you appreciate them today.' },
            { type: 'Dare', text: 'Do 10 jumping jacks together.' },
            { type: 'Dare', text: 'Practice 2 minutes of meditation together.' },
            { type: 'Dare', text: 'Write a thank you note for {partner}.' },
            { type: 'Dare', text: 'Research a place you want to travel to.' },
            { type: 'Dare', text: 'Give {partner} a high-five for a job well done.' },
            { type: 'Dare', text: 'Share a positive affirmation about {partner}.' },
            { type: 'Dare', text: 'Tidy up the living room together.' },
            { type: 'Dare', text: 'Play a game of Tic-Tac-Toe.' },
            { type: 'Dare', text: 'Make a list of 5 restaurants we should try.' },
            { type: 'Dare', text: 'Give {partner} a bear hug.' },
            { type: 'Dare', text: 'Offer a foot soak with warm water.' },
            { type: 'Dare', text: 'Read a poem to {partner}.' },
            { type: 'Dare', text: 'Find an interesting article to read together.' },
            { type: 'Dare', text: 'Give {partner} a gentle hand massage.' },
            { type: 'Dare', text: 'Do some light stretching with {partner}.' },
            { type: 'Dare', text: 'Make a toast to our partnership.' },
            { type: 'Dare', text: 'Fold a piece of laundry together.' },
            { type: 'Dare', text: 'Spend 5 minutes just talking, no distractions.' },
            { type: 'Dare', text: 'Give {partner} a long kiss on the cheek.' },
            { type: 'Dare', text: 'Put on a song and just sway together.' }
        ],
        funny: [
            { type: 'Truth', text: 'What is the most embarrassing thing that has happened to you recently?' },
            { type: 'Truth', text: 'If you were a cartoon character, which one would you be?' },
            { type: 'Truth', text: 'What is your most useless talent?' },
            { type: 'Truth', text: 'If we were in a zombie apocalypse, who would survive longer?' },
            { type: 'Truth', text: 'What is the weirdest habit you have?' },
            { type: 'Truth', text: 'What is the most ridiculous thing you have ever purchased?' },
            { type: 'Truth', text: 'If you could swap bodies with {partner} for a day, what is the first thing you would do?' },
            { type: 'Truth', text: 'What is the worst meal you have ever attempted to cook?' },
            { type: 'Truth', text: 'What is a word you have trouble pronouncing?' },
            { type: 'Truth', text: 'What is the funniest thing you have ever seen a pet do?' },
            { type: 'Truth', text: 'What was the worst haircut you ever got?' },
            { type: 'Truth', text: 'If you were a vegetable, which one would you be?' },
            { type: 'Truth', text: 'What is the silliest fear you have?' },
            { type: 'Truth', text: 'What is a fashion choice you regret from your teen years?' },
            { type: 'Truth', text: 'If you could only eat one food for the rest of your life, what would it be?' },
            { type: 'Truth', text: 'What is the most childish game you still love?' },
            { type: 'Truth', text: 'What is a bizarre food combination you enjoy?' },
            { type: 'Truth', text: 'Have you ever walked into a glass door?' },
            { type: 'Truth', text: 'What is a nickname you absolutely hate?' },
            { type: 'Truth', text: 'If you were an animal, which one would you be?' },
            { type: 'Truth', text: 'What is the most awkward text you have ever sent?' },
            { type: 'Truth', text: 'What is your go-to "karaoke" song?' },
            { type: 'Truth', text: 'What is the most useless fact you know?' },
            { type: 'Truth', text: 'What is your most embarrassing school memory?' },
            { type: 'Truth', text: 'What was your favorite cartoon growing up?' },
            { type: 'Truth', text: 'If you could live in any video game, which one would it be?' },
            { type: 'Truth', text: 'What is the strangest dream you have ever had?' },
            { type: 'Truth', text: 'If you had to be a ghost, who would you haunt?' },
            { type: 'Truth', text: 'What is the most annoying song you have stuck in your head?' },
            { type: 'Truth', text: 'What is the worst trend you ever followed?' },
            { type: 'Truth', text: 'If you could have any superpower but it’s completely useless, what would it be?' },
            { type: 'Truth', text: 'What was your first job and was it funny?' },
            { type: 'Truth', text: 'What is your most hated household chore?' },
            { type: 'Truth', text: 'What would your wrestler name be?' },
            { type: 'Truth', text: 'If you were a kitchen appliance, which one would you be?' },
            { type: 'Truth', text: 'What is a secret hobby you have that no one knows about?' },
            { type: 'Truth', text: 'What is the worst gift you have ever given?' },
            { type: 'Truth', text: 'If you could be a professional at anything, what would it be?' },
            { type: 'Truth', text: 'What is your biggest phobia that sounds funny to others?' },
            { type: 'Truth', text: 'What is a song that makes you want to dance uncontrollably?' },
            { type: 'Truth', text: 'If you could talk to any inanimate object, what would it be?' },
            { type: 'Truth', text: 'What is the most ridiculous movie you have ever watched?' },
            { type: 'Truth', text: 'If you were forced to eat a bug, which one would you pick?' },
            { type: 'Truth', text: 'What is your least favorite color?' },
            { type: 'Truth', text: 'What is the most awkward thing you have done on a date?' },
            { type: 'Truth', text: 'If you had to wear a costume all day, what would it be?' },
            { type: 'Truth', text: 'What is your favorite "dad joke"?' },
            { type: 'Truth', text: 'If you could design your own planet, what would it look like?' },
            { type: 'Truth', text: 'What is a weird quirk you have?' },
            { type: 'Truth', text: 'What is the most embarrassing thing you have ever said?' },
            { type: 'Dare', text: 'Try to do your best impression of {partner}.' },
            { type: 'Dare', text: 'Speak in a fake accent for the next 5 minutes.' },
            { type: 'Dare', text: 'Try to juggle three random items you find in the room.' },
            { type: 'Dare', text: 'Dance like nobody is watching for 1 minute.' },
            { type: 'Dare', text: 'Sing a nursery rhyme in an operatic voice.' },
            { type: 'Dare', text: 'Do your best impression of a chicken.' },
            { type: 'Dare', text: 'Make a silly face and hold it for 30 seconds.' },
            { type: 'Dare', text: 'Text a random emoji to your last contact.' },
            { type: 'Dare', text: 'Read a paragraph from a book using a ridiculous voice.' },
            { type: 'Dare', text: 'Try to walk like a penguin across the room.' },
            { type: 'Dare', text: 'Act like a monkey for 1 minute.' },
            { type: 'Dare', text: 'Give {partner} a piggyback ride across the room.' },
            { type: 'Dare', text: 'Sing the alphabet backwards.' },
            { type: 'Dare', text: 'Draw a funny mustache on your own face with eyeliner.' },
            { type: 'Dare', text: 'Tell a really bad joke.' },
            { type: 'Dare', text: 'Do an impression of a grumpy cat.' },
            { type: 'Dare', text: 'Try to fold a paper crane without instructions.' },
            { type: 'Dare', text: 'Do 5 burpees.' },
            { type: 'Dare', text: 'Write your name on the wall with your nose.' },
            { type: 'Dare', text: 'Talk like a robot for the next 3 minutes.' },
            { type: 'Dare', text: 'Attempt a cartwheel.' },
            { type: 'Dare', text: 'Do a funny dance.' },
            { type: 'Dare', text: 'Balance a spoon on your nose.' },
            { type: 'Dare', text: 'Sing a song about {partner} on the spot.' },
            { type: 'Dare', text: 'Put on a hat and wear it for the next hour.' },
            { type: 'Dare', text: 'Make up a story about a talking squirrel.' },
            { type: 'Dare', text: 'Try to imitate an opera singer.' },
            { type: 'Dare', text: 'Walk backwards for 1 minute.' },
            { type: 'Dare', text: 'Make a funny sound and repeat it.' },
            { type: 'Dare', text: 'Do a weird yoga pose.' },
            { type: 'Dare', text: 'Count to 50 as fast as you can.' },
            { type: 'Dare', text: 'Try to eat a piece of fruit without using your hands.' },
            { type: 'Dare', text: 'Do a silly walk.' },
            { type: 'Dare', text: 'Sing like a rockstar.' },
            { type: 'Dare', text: 'Imitate a dinosaur.' },
            { type: 'Dare', text: 'Make a weird face at {partner}.' },
            { type: 'Dare', text: 'Sing a nursery rhyme like a rapper.' },
            { type: 'Dare', text: 'Try to speak without using your lips.' },
            { type: 'Dare', text: 'Do 10 jumping jacks in a funny way.' },
            { type: 'Dare', text: 'Tell {partner} a secret with a weird accent.' },
            { type: 'Dare', text: 'Act like you are stuck in an elevator.' },
            { type: 'Dare', text: 'Create a silly dance move.' },
            { type: 'Dare', text: 'Sing the chorus of your least favorite song.' },
            { type: 'Dare', text: 'Do a silly pose for a photo.' },
            { type: 'Dare', text: 'Pretend you are an alien exploring the room.' },
            { type: 'Dare', text: 'Try to talk like a pirate.' },
            { type: 'Dare', text: 'Sing while making a funny face.' },
            { type: 'Dare', text: 'Walk in slow motion across the room.' },
            { type: 'Dare', text: 'Say "banana" 10 times in different voices.' },
            { type: 'Dare', text: 'Imitate a frog.' }
        ],
        naughty: [
            { type: 'Truth', text: 'What is your absolute favorite physical feature of {partner}?' },
            { type: 'Truth', text: 'Where is the most adventurous place you have ever been intimate?' },
            { type: 'Truth', text: 'What is one fantasy you have always wanted to act out?' },
            { type: 'Truth', text: 'What does {partner} do that instantly turns you on?' },
            { type: 'Truth', text: 'What is your favorite piece of lingerie or clothing on {partner}?' },
            { type: 'Truth', text: 'How would you describe your ideal romantic encounter?' },
            { type: 'Truth', text: 'What is a playful game you have wanted to try?' },
            { type: 'Truth', text: 'What is the most daring thing you have done to get {partner}\'s attention?' },
            { type: 'Truth', text: 'What is your favorite way to be kissed?' },
            { type: 'Truth', text: 'What is something you want to do to {partner} tonight?' },
            { type: 'Truth', text: 'What is the most attractive thing {partner} wears?' },
            { type: 'Truth', text: 'What is a scent on {partner} that drives you wild?' },
            { type: 'Truth', text: 'What is the most sensual gift you would like to receive?' },
            { type: 'Truth', text: 'What is your favorite way to be touched in public?' },
            { type: 'Truth', text: 'What is something you are dying to tell {partner}?' },
            { type: 'Truth', text: 'What is a role you would love for {partner} to play?' },
            { type: 'Truth', text: 'What is the most memorable date we have ever had?' },
            { type: 'Truth', text: 'What is a secret desire you have?' },
            { type: 'Truth', text: 'What is your favorite way to tease {partner}?' },
            { type: 'Truth', text: 'What is one thing you find so sexy about {partner}?' },
            { type: 'Truth', text: 'What is your favorite way to wake up {partner}?' },
            { type: 'Truth', text: 'What is a place you want to explore with {partner}?' },
            { type: 'Truth', text: 'What is the best part of our intimacy?' },
            { type: 'Truth', text: 'What do you want to explore more?' },
            { type: 'Truth', text: 'What makes you feel most confident?' },
            { type: 'Truth', text: 'What is a romantic gesture that turns you on?' },
            { type: 'Truth', text: 'What is your favorite part of a night in?' },
            { type: 'Truth', text: 'What do you love about how we flirt?' },
            { type: 'Truth', text: 'What is something you want to try together?' },
            { type: 'Truth', text: 'What is the most passionate kiss we have shared?' },
            { type: 'Truth', text: 'What is your favorite way to relax?' },
            { type: 'Truth', text: 'What is one thing you love about {partner}’s body?' },
            { type: 'Truth', text: 'What is the most exciting thing about our relationship?' },
            { type: 'Truth', text: 'What is a compliment you love receiving?' },
            { type: 'Truth', text: 'What is a fantasy you find intriguing?' },
            { type: 'Truth', text: 'How do you like to be led?' },
            { type: 'Truth', text: 'What is your favorite part of the day?' },
            { type: 'Truth', text: 'What do you think is our sexiest quality?' },
            { type: 'Truth', text: 'What is a way we can spice things up?' },
            { type: 'Truth', text: 'What is the best part of our connection?' },
            { type: 'Truth', text: 'What makes you feel wanted?' },
            { type: 'Truth', text: 'What is your favorite kind of intimacy?' },
            { type: 'Truth', text: 'What is something new you want to suggest?' },
            { type: 'Truth', text: 'What is your favorite way to be seduced?' },
            { type: 'Truth', text: 'What is a sweet thing {partner} does?' },
            { type: 'Truth', text: 'What is the most romantic thing we have planned?' },
            { type: 'Truth', text: 'What do you find most exciting?' },
            { type: 'Truth', text: 'What is a fun challenge for us?' },
            { type: 'Truth', text: 'What is your favorite part of being intimate?' },
            { type: 'Truth', text: 'What makes you feel most loved?' },
            { type: 'Dare', text: 'Give {partner} a 5-minute massage, focusing on areas they choose.' },
            { type: 'Dare', text: 'Whisper a secret fantasy into {partner}\'s ear.' },
            { type: 'Dare', text: 'Kiss {partner} for 30 seconds without stopping.' },
            { type: 'Dare', text: 'Slowly remove one article of {partner}\'s clothing.' },
            { type: 'Dare', text: 'Write a love note in a place {partner} will find it later.' },
            { type: 'Dare', text: 'Blindfold {partner} and give them a surprise touch.' },
            { type: 'Dare', text: 'Give {partner} a massage using a scented oil.' },
            { type: 'Dare', text: 'Sit in {partner}\'s lap and look into their eyes for a minute.' },
            { type: 'Dare', text: 'Tease {partner} by touching them without going all the way.' },
            { type: 'Dare', text: 'Feed {partner} a piece of fruit in a sensual way.' },
            { type: 'Dare', text: 'Kiss {partner}’s neck for 1 minute.' },
            { type: 'Dare', text: 'Give {partner} a deep, passionate kiss.' },
            { type: 'Dare', text: 'Run your fingers through {partner}’s hair.' },
            { type: 'Dare', text: 'Compliment {partner} on their body.' },
            { type: 'Dare', text: 'Gently kiss {partner}’s hands.' },
            { type: 'Dare', text: 'Give {partner} a massage on their neck and shoulders.' },
            { type: 'Dare', text: 'Tease {partner} by being playful.' },
            { type: 'Dare', text: 'Whisper something sweet into {partner}’s ear.' },
            { type: 'Dare', text: 'Trace {partner}’s lips with your finger.' },
            { type: 'Dare', text: 'Give {partner} a hug that lasts for 1 minute.' },
            { type: 'Dare', text: 'Kiss {partner} on the cheek repeatedly.' },
            { type: 'Dare', text: 'Sit close and hold hands.' },
            { type: 'Dare', text: 'Make {partner} laugh.' },
            { type: 'Dare', text: 'Give {partner} a massage on their feet.' },
            { type: 'Dare', text: 'Tell {partner} you’re excited for the night.' },
            { type: 'Dare', text: 'Take {partner}’s hand and kiss it.' },
            { type: 'Dare', text: 'Give {partner} a gentle back rub.' },
            { type: 'Dare', text: 'Whisper what you want to do tonight.' },
            { type: 'Dare', text: 'Look into {partner}’s eyes for 30 seconds.' },
            { type: 'Dare', text: 'Give {partner} a slow, lingering kiss.' },
            { type: 'Dare', text: 'Cuddle for 2 minutes.' },
            { type: 'Dare', text: 'Give {partner} a kiss on the ear.' },
            { type: 'Dare', text: 'Playfully tease {partner}.' },
            { type: 'Dare', text: 'Gently stroke {partner}’s arm.' },
            { type: 'Dare', text: 'Compliment {partner}’s outfit.' },
            { type: 'Dare', text: 'Give {partner} a shoulder rub.' },
            { type: 'Dare', text: 'Whisper a naughty thought.' },
            { type: 'Dare', text: 'Give {partner} a quick, intense kiss.' },
            { type: 'Dare', text: 'Trace patterns on {partner}’s back.' },
            { type: 'Dare', text: 'Kiss {partner}’s nose.' },
            { type: 'Dare', text: 'Hold {partner} close.' },
            { type: 'Dare', text: 'Give {partner} a gentle massage.' },
            { type: 'Dare', text: 'Tell {partner} they look amazing.' },
            { type: 'Dare', text: 'Give {partner} a soft kiss.' },
            { type: 'Dare', text: 'Play with {partner}’s hair.' },
            { type: 'Dare', text: 'Give {partner} a squeeze.' },
            { type: 'Dare', text: 'Kiss {partner}’s shoulder.' },
            { type: 'Dare', text: 'Be playful with {partner}.' },
            { type: 'Dare', text: 'Give {partner} a warm embrace.' },
            { type: 'Dare', text: 'Share a secret.' }
        ],
        adult: [
            { type: 'Truth', text: 'What is your deepest, darkest desire you haven\'t shared?' },
            { type: 'Truth', text: 'What is something you love that we have never tried?' },
            { type: 'Truth', text: 'Describe in detail how you would like to start your evening.' },
            { type: 'Truth', text: 'What is a roleplay scenario you would be interested in?' },
            { type: 'Truth', text: 'What is your favorite thing to do together when the lights are off?' },
            { type: 'Truth', text: 'What is the most intense experience we have ever shared?' },
            { type: 'Truth', text: 'What is a new technique you have been wanting to explore?' },
            { type: 'Truth', text: 'What do you find most irresistible about {partner}\'s body?' },
            { type: 'Truth', text: 'How do you like to be touched when we are alone?' },
            { type: 'Truth', text: 'What is one thing {partner} could do more often?' },
            { type: 'Truth', text: 'What is your absolute favorite part of our intimacy?' },
            { type: 'Truth', text: 'What is a fantasy you want to make a reality?' },
            { type: 'Truth', text: 'What is the most daring thing you want to do?' },
            { type: 'Truth', text: 'What is a role you want to play?' },
            { type: 'Truth', text: 'What is something that drives you wild?' },
            { type: 'Truth', text: 'What is a move that always gets a reaction?' },
            { type: 'Truth', text: 'What is something you are curious about?' },
            { type: 'Truth', text: 'What is the best way to get things going?' },
            { type: 'Truth', text: 'What is a fetish you might be interested in?' },
            { type: 'Truth', text: 'What makes you feel most liberated?' },
            { type: 'Truth', text: 'What is your favorite way to explore?' },
            { type: 'Truth', text: 'What is a technique you’ve heard of?' },
            { type: 'Truth', text: 'What do you think of roleplay?' },
            { type: 'Truth', text: 'What is the ultimate way to be intimate?' },
            { type: 'Truth', text: 'What is something you haven’t suggested?' },
            { type: 'Truth', text: 'What do you want more of?' },
            { type: 'Truth', text: 'What is your favorite way to play?' },
            { type: 'Truth', text: 'What is a scenario you find interesting?' },
            { type: 'Truth', text: 'What is your favorite way to use props?' },
            { type: 'Truth', text: 'What makes you feel most desired?' },
            { type: 'Truth', text: 'What do you find most seductive?' },
            { type: 'Truth', text: 'What is a boundary you’d like to explore?' },
            { type: 'Truth', text: 'What is a way we can keep things fresh?' },
            { type: 'Truth', text: 'What is the best part of our chemistry?' },
            { type: 'Truth', text: 'What do you think about being in control?' },
            { type: 'Truth', text: 'What is the most exciting thing about tonight?' },
            { type: 'Truth', text: 'What is your favorite way to touch?' },
            { type: 'Truth', text: 'What is a secret dream?' },
            { type: 'Truth', text: 'What is the best part of intimacy for you?' },
            { type: 'Truth', text: 'What do you want to try together?' },
            { type: 'Truth', text: 'What makes you feel most adventurous?' },
            { type: 'Truth', text: 'What is a scenario that sounds fun?' },
            { type: 'Truth', text: 'What is the most daring thing we have done?' },
            { type: 'Truth', text: 'What is a way to make things more intense?' },
            { type: 'Truth', text: 'What is the most attractive thing in our intimacy?' },
            { type: 'Truth', text: 'What is something you want to explore further?' },
            { type: 'Truth', text: 'What is a way to make things exciting?' },
            { type: 'Truth', text: 'What is your favorite way to be intimate?' },
            { type: 'Truth', text: 'What is a new experiment?' },
            { type: 'Truth', text: 'What makes you feel most connected?' },
            { type: 'Dare', text: 'Show {partner} a new move you have been reading about.' },
            { type: 'Dare', text: 'Explore a new area of your home together.' },
            { type: 'Dare', text: 'Spend the next 10 minutes focused entirely on {partner}\'s pleasure.' },
            { type: 'Dare', text: 'Use a toy or accessory if you have one available.' },
            { type: 'Dare', text: 'Try a position you haven’t done in a long time.' },
            { type: 'Dare', text: 'Take turns describing what you are feeling in detail.' },
            { type: 'Dare', text: 'Try a sensual massage session with no time limit.' },
            { type: 'Dare', text: 'Perform a striptease for {partner}.' },
            { type: 'Dare', text: 'Spend the next round completely undressed.' },
            { type: 'Dare', text: 'Whisper your deepest desires while being intimate.' },
            { type: 'Dare', text: 'Use a silk tie to blindfold {partner}.' },
            { type: 'Dare', text: 'Explore each other’s bodies with a feather.' },
            { type: 'Dare', text: 'Spend time focusing on slow, sensual touches.' },
            { type: 'Dare', text: 'Try a position that feels completely new.' },
            { type: 'Dare', text: 'Kiss {partner} from head to toe.' },
            { type: 'Dare', text: 'Take turns being in control.' },
            { type: 'Dare', text: 'Use ice to tease each other.' },
            { type: 'Dare', text: 'Try a game of "blindfold and guess".' },
            { type: 'Dare', text: 'Spend an hour just exploring intimacy.' },
            { type: 'Dare', text: 'Whisper sweet nothings.' },
            { type: 'Dare', text: 'Try a new scenario.' },
            { type: 'Dare', text: 'Be completely uninhibited.' },
            { type: 'Dare', text: 'Take turns describing your favorite touch.' },
            { type: 'Dare', text: 'Try something bold.' },
            { type: 'Dare', text: 'Focus on pure sensation.' },
            { type: 'Dare', text: 'Take it slow.' },
            { type: 'Dare', text: 'Be adventurous.' },
            { type: 'Dare', text: 'Explore new sensations.' },
            { type: 'Dare', text: 'Focus entirely on {partner}.' },
            { type: 'Dare', text: 'Try a new technique.' },
            { type: 'Dare', text: 'Use music to set the mood.' },
            { type: 'Dare', text: 'Experiment with light.' },
            { type: 'Dare', text: 'Try new positions.' },
            { type: 'Dare', text: 'Take turns guiding the experience.' },
            { type: 'Dare', text: 'Focus on pleasure.' },
            { type: 'Dare', text: 'Try something fun.' },
            { type: 'Dare', text: 'Spend time exploring.' },
            { type: 'Dare', text: 'Get creative.' },
            { type: 'Dare', text: 'Try something daring.' },
            { type: 'Dare', text: 'Take it step-by-step.' },
            { type: 'Dare', text: 'Enjoy the moment.' },
            { type: 'Dare', text: 'Explore together.' },
            { type: 'Dare', text: 'Try a new rhythm.' },
            { type: 'Dare', text: 'Focus on sensations.' },
            { type: 'Dare', text: 'Get playful.' },
            { type: 'Dare', text: 'Take the lead.' },
            { type: 'Dare', text: 'Try something spontaneous.' },
            { type: 'Dare', text: 'Be completely open.' },
            { type: 'Dare', text: 'Explore each other.' },
            { type: 'Dare', text: 'Try a new adventure.' }
        ]
    },
    'never-have-i-ever': {
        title: 'Never Have I Ever',
        normal: [
            'Never have I ever gone on a surprise weekend trip.',
            'Never have I ever cooked a full meal for {partner}.',
            'Never have I ever written a love letter.',
            'Never have I ever been to a concert with {partner}.',
            'Never have I ever taken a dance class.',
            'Never have I ever gone stargazing with {partner}.',
            'Never have I ever watched a movie marathon all night.',
            'Never have I ever made a playlist for {partner}.',
            'Never have I ever been hiking on a scenic trail.',
            'Never have I ever learned to bake something from scratch for {partner}.',
            'Never have I ever planned a secret celebration for {partner}.',
            'Never have I ever taken a spontaneous road trip.',
            'Never have I ever stayed up all night talking to {partner}.',
            'Never have I ever gone camping under the stars.',
            'Never have I ever finished a 1,000-piece puzzle.',
            'Never have I ever taken a professional photo together.',
            'Never have I ever visited a botanical garden.',
            'Never have I ever tried a new cuisine at a local market.',
            'Never have I ever watched the sunrise with {partner}.',
            'Never have I ever gone to a museum for an afternoon.',
            'Never have I ever made breakfast in bed for {partner}.',
            'Never have I ever gone berry picking.',
            'Never have I ever built a sandcastle together.',
            'Never have I ever gone to a bookstore and picked books for each other.',
            'Never have I ever spent an entire day just laughing.',
            'Never have I ever written down a list of things I love about {partner}.',
            'Never have I ever gone on a sunrise hike.',
            'Never have I ever learned to paint together.',
            'Never have I ever gone to a local farmers market.',
            'Never have I ever tried a new sport with {partner}.',
            'Never have I ever spent a weekend offline.',
            'Never have I ever gone on a winter walk.',
            'Never have I ever planned a romantic picnic.',
            'Never have I ever gone to a comedy show.',
            'Never have I ever visited a new city together.',
            'Never have I ever gone to a drive-in movie.',
            'Never have I ever cooked a meal from a different culture.',
            'Never have I ever gone for a bike ride.',
            'Never have I ever looked through old photo albums.',
            'Never have I ever shared a heartfelt memory.',
            'Never have I ever gone out for dessert.',
            'Never have I ever spent an evening just listening to music.',
            'Never have I ever tried a new coffee shop.',
            'Never have I ever made a vision board together.',
            'Never have I ever been to a local fair.',
            'Never have I ever enjoyed a long brunch.',
            'Never have I ever gone for a walk in the rain.',
            'Never have I ever shared a secret dream.',
            'Never have I ever had a game night.',
            'Never have I ever done a craft together.'
        ],
        funny: [
            'Never have I ever accidentally sent a text to the wrong person.',
            'Never have I ever tripped in public and acted like nothing happened.',
            'Never have I ever laughed so hard that I snorted.',
            'Never have I ever tried a DIY project that turned into a disaster.',
            'Never have I ever talked to myself out loud.',
            'Never have I ever had a dream that I was a famous celebrity.',
            'Never have I ever tried to dance but ended up looking like a fish out of water.',
            'Never have I ever forgotten where I put my keys while I was holding them.',
            'Never have I ever accidentally called a teacher "Mom".',
            'Never have I ever tried to eat something super spicy and regretted it instantly.',
            'Never have I ever walked into a glass door.',
            'Never have I ever tried to do a cartwheel and failed miserably.',
            'Never have I ever fallen asleep in a movie theater.',
            'Never have I ever gotten something stuck in my hair.',
            'Never have I ever been scared of my own shadow.',
            'Never have I ever tried to cook something and set off the smoke alarm.',
            'Never have I ever had a bad haircut that I tried to fix myself.',
            'Never have I ever accidentally dyed my clothes pink.',
            'Never have I ever tripped over my own feet.',
            'Never have I ever tried to say a word and ended up making a weird sound.',
            'Never have I ever forgotten how to spell a simple word.',
            'Never have I ever got a song stuck in my head for days.',
            'Never have I ever tried to juggle and dropped everything immediately.',
            'Never have I ever made a funny face and got stuck like that.',
            'Never have I ever tried to walk while wearing heels and tripped.',
            'Never have I ever had a wardrobe malfunction in public.',
            'Never have I ever laughed at a joke I didn’t understand.',
            'Never have I ever accidentally insulted someone by mistake.',
            'Never have I ever tried to bake and added salt instead of sugar.',
            'Never have I ever fallen off a chair.',
            'Never have I ever accidentally walked into the wrong room.',
            'Never have I ever tried a trend that looked ridiculous on me.',
            'Never have I ever forgotten where I parked my car.',
            'Never have I ever had an awkward conversation with a stranger.',
            'Never have I ever tried to sing a song and forgotten the words.',
            'Never have I ever accidentally liked an old photo on social media.',
            'Never have I ever gotten lost in my own town.',
            'Never have I ever tripped on a flat surface.',
            'Never have I ever had an embarrassing moment on a video call.',
            'Never have I ever tried to do a dance and looked ridiculous.',
            'Never have I ever had a weird food craving at 2 AM.',
            'Never have I ever called a store clerk by the wrong name.',
            'Never have I ever accidentally worn my shirt inside out.',
            'Never have I ever tried to fix a leak and made it worse.',
            'Never have I ever had a moment where I just stood there confused.',
            'Never have I ever tried to be cool and failed.',
            'Never have I ever had a funny misunderstanding.',
            'Never have I ever tried to say something clever and stumbled.',
            'Never have I ever been caught daydreaming by everyone.',
            'Never have I ever made a mistake that turned into a hilarious story.'
        ],
        naughty: [
            'Never have I ever flirted with {partner} in a public place.',
            'Never have I ever sent a spicy text message.',
            'Never have I ever had a dream about {partner}.',
            'Never have I ever tried to seduce {partner} during a movie.',
            'Never have I ever had an intense make-out session in a car.',
            'Never have I ever used a piece of fruit in a romantic way.',
            'Never have I ever worn something special specifically for {partner}.',
            'Never have I ever initiated a romantic encounter in a random location.',
            'Never have I ever been caught by someone while being intimate.',
            'Never have I ever roleplayed with {partner}.',
            'Never have I ever sent a picture meant only for {partner}.',
            'Never have I ever tried to surprise {partner} while they were getting dressed.',
            'Never have I ever had a romantic night under the stars.',
            'Never have I ever flirted with {partner} using hidden messages.',
            'Never have I ever been intimate in the kitchen.',
            'Never have I ever used scented oil for a massage.',
            'Never have I ever whispered a secret fantasy.',
            'Never have I ever been adventurous with {partner}.',
            'Never have I ever had a long, slow kiss in a public space.',
            'Never have I ever worn something hidden under my clothes for {partner}.',
            'Never have I ever initiated a game of touch.',
            'Never have I ever tried something new to spice up the night.',
            'Never have I ever given {partner} a massage when they weren’t expecting it.',
            'Never have I ever flirted with {partner} through a long distance.',
            'Never have I ever made {partner} blush on purpose.',
            'Never have I ever sent a song that reminds me of our chemistry.',
            'Never have I ever tried a new position I was curious about.',
            'Never have I ever planned a surprise night of romance.',
            'Never have I ever been playfully teased by {partner}.',
            'Never have I ever had a moment of intense connection.',
            'Never have I ever worn perfume/cologne specifically to turn {partner} on.',
            'Never have I ever had a lingering gaze across a crowded room.',
            'Never have I ever touched {partner} in a way that made their heart race.',
            'Never have I ever whispered something sweet.',
            'Never have I ever been on a romantic trip.',
            'Never have I ever tried to flirt when we had guests.',
            'Never have I ever sent a note in a secret place.',
            'Never have I ever shared a look that said everything.',
            'Never have I ever had an intense embrace.',
            'Never have I ever been playful.',
            'Never have I ever planned a romantic dinner.',
            'Never have I ever tried to be seductive.',
            'Never have I ever shared a secret.',
            'Never have I ever been daring.',
            'Never have I ever had a long kiss.',
            'Never have I ever been intimate.',
            'Never have I ever tried something bold.',
            'Never have I ever been mischievous.',
            'Never have I ever shared a romantic moment.',
            'Never have I ever been passionate.'
        ],
        adult: [
            'Never have I ever tried a position I saw in a movie.',
            'Never have I ever been intimate in a public place.',
            'Never have I ever used blindfolds for fun.',
            'Never have I ever had a marathon session that lasted all night.',
            'Never have I ever tried something brand new together.',
            'Never have I ever been extremely adventurous with {partner}.',
            'Never have I ever used props or toys to enhance the mood.',
            'Never have I ever had a shower session together.',
            'Never have I ever been completely uninhibited.',
            'Never have I ever explored the boundaries of our intimacy.',
            'Never have I ever tried roleplay in a new scenario.',
            'Never have I ever used aromatherapy during a night of fun.',
            'Never have I ever had a session that lasted for hours.',
            'Never have I ever been adventurous with location.',
            'Never have I ever explored new techniques.',
            'Never have I ever been completely vulnerable.',
            'Never have I ever used soft restraints.',
            'Never have I ever had an intense experience together.',
            'Never have I ever tried something that scared me a little.',
            'Never have I ever been completely honest about a desire.',
            'Never have I ever tried a new sensory experience.',
            'Never have I ever had a night dedicated to pure exploration.',
            'Never have I ever been playful with boundaries.',
            'Never have I ever tried a new role.',
            'Never have I ever had an unforgettable experience.',
            'Never have I ever shared a deepest desire.',
            'Never have I ever been completely in the moment.',
            'Never have I ever used new tools.',
            'Never have I ever explored deeper intimacy.',
            'Never have I ever been totally wild.',
            'Never have I ever had a long, slow session.',
            'Never have I ever tried something daring.',
            'Never have I ever been completely adventurous.',
            'Never have I ever shared a new sensation.',
            'Never have I ever had a breakthrough.',
            'Never have I ever tried something bold.',
            'Never have I ever been totally lost in the moment.',
            'Never have I ever explored new limits.',
            'Never have I ever tried a new approach.',
            'Never have I ever had a deeply intense night.',
            'Never have I ever been completely open.',
            'Never have I ever tried a new dynamic.',
            'Never have I ever had a uniquely romantic session.',
            'Never have I ever been adventurous in our routine.',
            'Never have I ever shared everything.',
            'Never have I ever tried a new style.',
            'Never have I ever had an all-consuming experience.',
            'Never have I ever explored our connection.',
            'Never have I ever tried something completely different.',
            'Never have I ever been totally in sync.'
        ]
    },
    'would-you-rather': {
        title: 'Would You Rather',
        normal: [
            'Would you rather travel the world with {partner} or stay in a cozy home forever?',
            'Would you rather receive a handwritten letter or a thoughtful gift?',
            'Would you rather have a quiet night in or a big night out?',
            'Would you rather live by the beach or in the mountains?',
            'Would you rather have a personal chef or a personal cleaner?',
            'Would you rather always have great weather or always be comfortable?',
            'Would you rather have more time or more money?',
            'Would you rather be able to read minds or predict the future?',
            'Would you rather have a superpower or be able to travel through time?',
            'Would you rather always be early or always be on time?',
            'Would you rather be famous or anonymous?',
            'Would you rather live in a house full of books or a house full of art?',
            'Would you rather have a private jet or a luxury yacht?',
            'Would you rather always speak your mind or always be silent?',
            'Would you rather have eternal youth or immense wisdom?',
            'Would you rather always have a dog or always have a cat?',
            'Would you rather live in the city or the countryside?',
            'Would you rather be able to sing beautifully or play any instrument?',
            'Would you rather have a magical garden or a magical library?',
            'Would you rather travel to the past or the future?',
            'Would you rather be a master chef or a master baker?',
            'Would you rather live in a hot climate or a cold climate?',
            'Would you rather have a small cozy house or a big mansion?',
            'Would you rather be able to fly or be invisible?',
            'Would you rather have a delicious meal every day or a great travel experience every month?',
            'Would you rather be a famous scientist or a famous artist?',
            'Would you rather live by a lake or in the woods?',
            'Would you rather always be dressed up or always be comfortable?',
            'Would you rather have a pet dragon or a pet unicorn?',
            'Would you rather always work from home or always work at an office?',
            'Would you rather go on a hike or go for a swim?',
            'Would you rather have a home cinema or a home gym?',
            'Would you rather eat only savory food or only sweet food?',
            'Would you rather always be the smartest person or the most popular person?',
            'Would you rather travel to Europe or Asia?',
            'Would you rather be a writer or a musician?',
            'Would you rather have an unlimited budget for books or for travel?',
            'Would you rather live in a treehouse or a lighthouse?',
            'Would you rather always listen to jazz or always listen to classical music?',
            'Would you rather be a master gardener or a master cook?',
            'Would you rather live in an apartment or a house?',
            'Would you rather always have coffee or tea?',
            'Would you rather go on a mountain adventure or a beach vacation?',
            'Would you rather have a home sauna or a swimming pool?',
            'Would you rather be an expert at painting or sculpting?',
            'Would you rather live near the ocean or near a lake?',
            'Would you rather always be in charge or have someone else lead?',
            'Would you rather have a beautiful garden or a rooftop terrace?',
            'Would you rather live in a castle or a cabin?',
            'Would you rather travel alone or with {partner}?'
        ],
        funny: [
            'Would you rather always have to sing instead of speaking or dance everywhere you walk?',
            'Would you rather have a tail or ears like a dog?',
            'Would you rather have to wear a clown nose or oversized shoes every day?',
            'Would you rather fight one horse-sized duck or 100 duck-sized horses?',
            'Would you rather have your hair grow an inch every day or your nails grow an inch every day?',
            'Would you rather be able to talk to animals or be able to fly?',
            'Would you rather always sound like a chipmunk or sound like a robot?',
            'Would you rather have to eat a lemon every morning or a hot pepper every night?',
            'Would you rather be famous for something stupid or unknown for being a genius?',
            'Would you rather have a tiny head or giant hands?',
            'Would you rather have to walk on all fours or crawl everywhere?',
            'Would you rather have a permanent nose whistle or a permanent sneeze?',
            'Would you rather have to speak in rhymes or speak in riddles?',
            'Would you rather have to wear a giant hat or giant boots?',
            'Would you rather eat only pizza or only chocolate?',
            'Would you rather be able to communicate with plants or with kitchen appliances?',
            'Would you rather have a pet rock or a pet dust bunny?',
            'Would you rather always feel like you’re falling or always feel like you’re floating?',
            'Would you rather have to wear a tutu every day or a cape every day?',
            'Would you rather have to sing the national anthem before every meal or dance before every drink?',
            'Would you rather be able to change colors like a chameleon or move like a slinky?',
            'Would you rather have to wear your clothes backwards or inside out?',
            'Would you rather have a clown follow you or a mime follow you?',
            'Would you rather have to say "meow" after every sentence or "quack" after every sentence?',
            'Would you rather have a permanent unibrow or no eyebrows at all?',
            'Would you rather have to do a funny walk everywhere or a funny dance?',
            'Would you rather have to speak only in movie quotes or only in song lyrics?',
            'Would you rather eat only soup for a month or only toast for a month?',
            'Would you rather always have blue hair or always have a mohawk?',
            'Would you rather have to wear a mask of your own face or a mask of someone else’s?',
            'Would you rather have hands for feet or feet for hands?',
            'Would you rather have a nose that grows when you lie or ears that grow when you tell the truth?',
            'Would you rather have a permanent bedhead or permanent messy hair?',
            'Would you rather always wear pajamas or always wear a suit?',
            'Would you rather have to sing every word you say or whisper every word you say?',
            'Would you rather always have a tiny umbrella or always have a tiny hat?',
            'Would you rather have to hop everywhere or skip everywhere?',
            'Would you rather have a pet chicken or a pet goat?',
            'Would you rather eat only green food or only red food?',
            'Would you rather be able to fly but only at 1 mph or be able to run at 100 mph but only while blindfolded?',
            'Would you rather have to wear clown makeup every day or clown shoes every day?',
            'Would you rather always sound like you have a cold or always sound like you’re yelling?',
            'Would you rather have to sleep on the floor or sleep on the ceiling?',
            'Would you rather always have a leaf in your hair or a pebble in your shoe?',
            'Would you rather have to whistle every time you’re happy or hum every time you’re sad?',
            'Would you rather have a permanent itchy nose or a permanent itchy back?',
            'Would you rather have to carry a giant pencil everywhere or a giant eraser?',
            'Would you rather always wear socks with sandals or crocs?',
            'Would you rather have a permanent mustache or a permanent uni-brow?',
            'Would you rather always smell like bacon or always smell like onions?'
        ],
        naughty: [
            'Would you rather have a long massage or a passionate kiss?',
            'Would you rather have a romantic dinner or a wild night in?',
            'Would you rather have a playful chase or a slow dance?',
            'Would you rather be teased or be the one teasing?',
            'Would you rather have your neck kissed or your ears whispered to?',
            'Would you rather have {partner} take the lead or be the one in control?',
            'Would you rather spend the night cuddling or exploring new things?',
            'Would you rather receive a surprise visit or a planned romantic evening?',
            'Would you rather have the lights on or off?',
            'Would you rather have a slow start or a fast finish?',
            'Would you rather have a long bath together or a hot shower together?',
            'Would you rather spend an evening in lingerie or in something cozy?',
            'Would you rather be seduced by words or by touch?',
            'Would you rather have a playful game or a deep conversation?',
            'Would you rather have your partner be the one to choose the activity or you choose?',
            'Would you rather have a gentle touch or a firm touch?',
            'Would you rather spend the night in the living room or the bedroom?',
            'Would you rather have a surprise kiss or a surprise massage?',
            'Would you rather have a romantic playlist or silence?',
            'Would you rather have a candlelit setting or something more natural?',
            'Would you rather have a playful tease or a direct approach?',
            'Would you rather spend the night focused on {partner} or {partner} focused on you?',
            'Would you rather have a slow, sensual pace or something faster?',
            'Would you rather have a game of hide-and-seek or something more relaxing?',
            'Would you rather have your hair played with or your hands held?',
            'Would you rather spend the evening in silk or in cotton?',
            'Would you rather have your partner choose your outfit or you choose?',
            'Would you rather have a private dance or a private conversation?',
            'Would you rather be surprised with a gift or with an experience?',
            'Would you rather have a long, lazy morning or an adventurous night?',
            'Would you rather have a deep look into your eyes or a sweet kiss?',
            'Would you rather have a playful tickle or a gentle caress?',
            'Would you rather have your partner whisper your name or whisper your desires?',
            'Would you rather have a romantic trip or a staycation?',
            'Would you rather have a slow massage or a quick, intense one?',
            'Would you rather have everything planned or let things be spontaneous?',
            'Would you rather be the one in control or be the one who surrenders?',
            'Would you rather spend time in the kitchen or the bedroom?',
            'Would you rather have a romantic evening or a fun night?',
            'Would you rather have a quiet night or a loud night?',
            'Would you rather have a warm touch or a cooling touch?',
            'Would you rather have your partner be bold or be subtle?',
            'Would you rather spend the night focused on intimacy or pleasure?',
            'Would you rather have everything ready or do it on the fly?',
            'Would you rather have an adventurous evening or a relaxing one?',
            'Would you rather have a special scent or your partner’s natural scent?',
            'Would you rather be in a room full of candles or in the moonlight?',
            'Would you rather have your partner take the first step or you take it?',
            'Would you rather be surprised or know what to expect?',
            'Would you rather have a long, slow encounter or a short, intense one?'
        ],
        adult: [
            'Would you rather try something completely new or stick to your favorite routine?',
            'Would you rather be the one in control or surrender control?',
            'Would you rather focus on a long, slow session or intense, quick fun?',
            'Would you rather be completely uninhibited or slightly mysterious?',
            'Would you rather try roleplay or keep things realistic?',
            'Would you rather spend the entire day in bed or go for a daring adventure?',
            'Would you rather focus on intimacy or pure excitement?',
            'Would you rather have everything planned or let things happen naturally?',
            'Would you rather be vocal or silent?',
            'Would you rather have a relaxing massage or an active night?',
            'Would you rather explore a new technique or stick to your comfort zone?',
            'Would you rather be the one who initiates or the one who is surprised?',
            'Would you rather have a session that is all about exploration or all about pleasure?',
            'Would you rather use props or keep it completely natural?',
            'Would you rather try a new location or a new style?',
            'Would you rather be completely focused on each other or a bit distracted?',
            'Would you rather have an intense, all-consuming experience or something more laid back?',
            'Would you rather try a new position or go back to an old favorite?',
            'Would you rather have a night of mystery or a night of total transparency?',
            'Would you rather be experimental or traditional?',
            'Would you rather try a new sensory experience or stick to the basics?',
            'Would you rather have everything set up beforehand or spontaneous fun?',
            'Would you rather try something bold or stick to your usual dynamic?',
            'Would you rather have your partner lead or lead them yourself?',
            'Would you rather explore deeper intimacy or just have some fun?',
            'Would you rather have a long, sustained experience or many short ones?',
            'Would you rather be completely vulnerable or keep some mystery?',
            'Would you rather try something that challenges you or stick to your strengths?',
            'Would you rather focus on physical pleasure or mental connection?',
            'Would you rather have a night that is purely romantic or purely exciting?',
            'Would you rather try a new way to be intimate or stick to your routine?',
            'Would you rather have complete freedom or some guidelines?',
            'Would you rather focus on a long session or something short and fast?',
            'Would you rather be very vocal about your desires or very subtle?',
            'Would you rather have everything planned to the minute or let it unfold?',
            'Would you rather try something new or refine your favorite technique?',
            'Would you rather focus on pleasure or on exploration?',
            'Would you rather have an adventurous evening or a deeply intimate one?',
            'Would you rather have a night where everything is allowed or a night with limits?',
            'Would you rather be bold or stay comfortable?',
            'Would you rather have complete silence or total communication?',
            'Would you rather try a new dynamic or stick to your established roles?',
            'Would you rather have a night of total relaxation or total stimulation?',
            'Would you rather explore your limits or play within your comfort zone?',
            'Would you rather focus on the journey or the destination?',
            'Would you rather try something completely different or stick to your best? ',
            'Would you rather have an intense night or a relaxing one?',
            'Would you rather focus on each other or the environment?',
            'Would you rather have complete control or give it up?',
            'Would you rather try a new approach or perfect your classic style?'
        ]
    },
    'date-idea': {
        title: 'Date Generator',
        normal: [
            'Have a picnic in the park.',
            'Cook a new recipe together.',
            'Visit a local museum.',
            'Go for a long walk and grab ice cream.',
            'Have a movie night at home with blankets and popcorn.',
            'Take a scenic drive to the countryside.',
            'Go to a farmers market and pick ingredients for dinner.',
            'Visit a nearby botanical garden.',
            'Have a board game tournament.',
            'Go star gazing with a thermos of hot chocolate.',
            'Visit a local zoo.',
            'Spend an afternoon at a bookstore.',
            'Go to an art gallery.',
            'Visit a local park and fly a kite.',
            'Go on a hike and have lunch at the top.',
            'Try a new brunch spot.',
            'Go to a cooking class together.',
            'Visit a local landmark.',
            'Go to a beach and walk along the shore.',
            'Have a cozy dinner at home with candles.',
            'Visit a local market and try everything.',
            'Go for a bike ride around the city.',
            'Go on a treasure hunt in the city.',
            'Visit a nearby aquarium.',
            'Have a backyard campfire.',
            'Go on a city walking tour.',
            'Take a pottery class.',
            'Visit a butterfly house.',
            'Go to a drive-in theater.',
            'Have a long breakfast at a cafe.',
            'Go stargazing away from the city lights.',
            'Visit a planetarium.',
            'Go on a brewery or winery tour.',
            'Have a game night with friends.',
            'Go to a local theater production.',
            'Visit a historical site.',
            'Go on a waterfall hike.',
            'Spend a rainy day playing board games.',
            'Visit a garden center and buy a new plant.',
            'Go on a coffee tasting tour.',
            'Have a DIY home spa day.',
            'Visit a local craft brewery.',
            'Go for a drive at sunset.',
            'Have a movie marathon of your favorite series.',
            'Visit a local park and have a picnic.',
            'Go on a short hiking trip.',
            'Spend time playing cards.',
            'Go to a local library.',
            'Try to bake bread from scratch.',
            'Spend an afternoon just talking.'
        ],
        funny: [
            'Go to a thrift store and pick outfits for each other.',
            'Try to learn a TikTok dance together.',
            'Have a bake-off where you make something silly.',
            'Visit a comedy club for open mic night.',
            'Take a painting class where you paint each other.',
            'Have a water balloon fight in the backyard.',
            'Try a "no-hands" eating challenge.',
            'Go to a pet store and play with the animals.',
            'Try a "mystery taste test" challenge.',
            'Go to a karaoke bar and sing the most ridiculous songs.',
            'Try to build a fort in the living room.',
            'Go to a playground and swing on the swings.',
            'Try to learn a magic trick.',
            'Go to an arcade and play old-school games.',
            'Have a "fancy dress" dinner at home.',
            'Try a weird craft project.',
            'Go to a park and feed the ducks.',
            'Have a contest to see who can draw the best portrait of the other.',
            'Try to recreate a childhood favorite snack.',
            'Go to a trampoline park.',
            'Try to learn to hula hoop.',
            'Go to a costume shop and try on the wildest things.',
            'Have a dance-off in the living room.',
            'Try a "blindfolded drawing" challenge.',
            'Go to a cat cafe.',
            'Try to make an elaborate paper airplane.',
            'Have a race to see who can clean a room the fastest.',
            'Try a challenge from a random internet video.',
            'Go to a park and do people watching.',
            'Try to learn to juggle.',
            'Have a "mismatched" outfit contest.',
            'Go to a bookstore and hide funny notes in books.',
            'Try to learn a new silly skill.',
            'Go to a park and play tag.',
            'Try to make a sculpture out of clay.',
            'Go to a local diner and order the weirdest thing.',
            'Try to do a yoga session with a funny video.',
            'Go to a toy store and play with the stuff.',
            'Have a contest to see who can write the funniest poem.',
            'Try a new food and guess what’s in it.',
            'Go to a park and try to fly a frisbee.',
            'Try to make your own board game.',
            'Go to a store and see who can find the silliest item.',
            'Try to paint with your feet.',
            'Go to a playground and climb on everything.',
            'Try to do an impression of a celebrity.',
            'Have a race to see who can make the weirdest face.',
            'Try a new exercise video.',
            'Go to a library and find funny book titles.',
            'Try to learn a new language word by word.'
        ],
        naughty: [
            'Go for a late-night drive to a secluded spot.',
            'Stay in and have a candlelit massage session.',
            'Have a romantic bath together with rose petals.',
            'Try to cook dinner together wearing as little as possible.',
            'Plan a weekend away at a cozy hotel.',
            'Go for an evening walk and find a spot to share a private moment.',
            'Give each other a full-body massage with scented oils.',
            'Visit a hotel bar for drinks and flirt all night.',
            'Have a "no-phone" night focused on each other.',
            'Dance slow in the kitchen with music and low light.',
            'Spend an evening in a private room.',
            'Try a night of blindfolded intimacy.',
            'Go for a walk after dark.',
            'Create a cozy spot at home.',
            'Have an evening in soft lighting.',
            'Give each other a sensual massage.',
            'Dance to your favorite song.',
            'Spend an evening focusing on each other.',
            'Try an evening of roleplay.',
            'Have a romantic wine tasting.',
            'Try something bold at home.',
            'Spend an evening in loungewear.',
            'Have a long, lingering kiss.',
            'Explore each other in the dark.',
            'Spend time playing games.',
            'Try an evening of seduction.',
            'Go for a late night stroll.',
            'Spend time in the bedroom.',
            'Have a night of indulgence.',
            'Give each other full attention.',
            'Spend an evening in intimacy.',
            'Try something different.',
            'Have a night of fun.',
            'Explore your connection.',
            'Spend time in private.',
            'Try a new activity.',
            'Have a night of romance.',
            'Get close.',
            'Try something new.',
            'Have a special evening.',
            'Explore intimacy.',
            'Spend quality time.',
            'Try something exciting.',
            'Have a romantic night.',
            'Get intimate.',
            'Explore together.',
            'Try a new style.',
            'Have a night of passion.',
            'Get creative.',
            'Try something daring.'
        ],
        adult: [
            'Book a private room for a special dinner.',
            'Visit an adult toy store together.',
            'Plan a weekend getaway focused on intimacy.',
            'Create a private space at home and make it your "sanctuary".',
            'Spend the entire day in the bedroom.',
            'Explore a new type of class (e.g., adult dance or art).',
            'Try a "day of yes" where everything is allowed.',
            'Go for a spontaneous trip to a nearby city.',
            'Visit a clothing-optional beach if you are feeling adventurous.',
            'Spend the night at a luxury spa hotel.',
            'Plan a surprise night in a private space.',
            'Try an evening of roleplay with props.',
            'Visit a private lounge or club.',
            'Spend a whole day dedicated to each other.',
            'Explore a new level of intimacy.',
            'Try an evening of total sensory exploration.',
            'Spend a romantic weekend in a secluded cabin.',
            'Have an evening of deep exploration.',
            'Try a new dynamic at home.',
            'Explore your deepest desires together.',
            'Visit a boutique hotel.',
            'Spend time in a private sauna.',
            'Try an adventurous activity.',
            'Explore new techniques.',
            'Spend a night of total immersion.',
            'Have a special weekend escape.',
            'Try a night of roleplay.',
            'Visit an exclusive lounge.',
            'Spend time in a sanctuary.',
            'Explore deeper connection.',
            'Try a new dynamic.',
            'Have a night of total freedom.',
            'Explore intimacy fully.',
            'Spend a special day.',
            'Try something bold.',
            'Visit a unique location.',
            'Spend a night together.',
            'Explore your bond.',
            'Try something new.',
            'Have a night of indulgence.',
            'Get intimate.',
            'Explore together.',
            'Try a new style.',
            'Have a night of passion.',
            'Get creative.',
            'Try something daring.',
            'Spend time exploring.',
            'Have a romantic night.',
            'Get closer.',
            'Try something different.'
        ]
    }
};
